name:                symmath
version:             0.1.0.0
github:              "byronwan/symmath"
license:             BSD3
author:              "ByronWan"
maintainer:          "byronwan@outlook.com"
copyright:           "2022 ByronWan here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/symmath#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  symmath-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symmath

tests:
  symmath-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symmath
